### ISSUE TITLE
Crash when put character png into subfolder

### ISSUE THREAD

**Issue by gritsenko** [gritsenko/c3_spine_plugin#86]
When I put spine character into subfolder, it gives following loading errors:

```
Failed to load resource: the server responded with a status of 404 ()
ddd6be46-bd8d-479f-89e0-6ff1900d7715:4069 Uncaught (in promise) TypeError: this.atlas.findRegion is not a function
    at AtlasAttachmentLoader.newRegionAttachment (ddd6be46-bd8d-479f-89e0-6ff1900d7715:4069:33)
    at SkeletonJson.readAttachment (ddd6be46-bd8d-479f-89e0-6ff1900d7715:8534:46)
    at SkeletonJson.readSkeletonData (ddd6be46-bd8d-479f-89e0-6ff1900d7715:8480:37)
    at SpineInstance.loadSkeletonData (5bfb184b-8e6a-47ac-8d41-7d0fd82d035d:257:69)
    at SpineInstance.IsSpineReady (5bfb184b-8e6a-47ac-8d41-7d0fd82d035d:624:26)
    at SpineInstance.Tick (5bfb184b-8e6a-47ac-8d41-7d0fd82d035d:710:18)
    at Array._tickFunc (sdkInstanceBase.js:6:186)
    at EventHandler._FireNonCancellable (handler.js:7:27)
    at EventDispatcher.dispatchEvent (dispatcher.js:4:235)
    at C3Runtime.Step_AfterPreTick (runtime.js:81:318)
```

![image](https://user-images.githubusercontent.com/2227312/213999566-de5a6822-71e9-4364-90de-c7035abb5a16.png)

![image](https://user-images.githubusercontent.com/2227312/213999598-d888e8e2-9756-4004-a628-63c25a3727f6.png)

![image](https://user-images.githubusercontent.com/2227312/213999449-b8c4ed8b-fae0-477d-bfa3-79ac7cf77b4f.png)

### Sample project
[subfolder_problem.zip](https://github.com/gritsenko/c3_spine_plugin/files/10478078/subfolder_problem.zip)

If I put PNG file into root folder and keep json and atals in subfolder everything working normally

**Comment by MikalDev** [comment]
Try editing the first line of the atlas file to include the directory name to the png.

**Comment by XHXIAIEIN** [comment]
I also have this problem, but I don't know how to solve it correctly. My JSON does not contain the directory path.(Using 4.1.24)

![Snipaste_2023-12-18_20-57-48](https://github.com/gritsenko/c3_spine_plugin/assets/45864744/7990b8a4-9f9b-41f6-9215-80a6a4697622)
